### ISSUE TITLE
Toroidal movement

### ISSUE THREAD

**Issue by andagel** [squee72564/F0_Minesweeper_Fap#7]
**Is your feature request related to a problem? Please describe.**
It takes a lot of clicks to reach the opposite edge of the screen.

**Describe the solution you'd like**
Allow wrapping location: when on left edge, moving left brings the cursor on the right edge. Same on the other side, and for top and bottom.
In C that would be conceptually like modulo-fieldsize coordinates (current_position % fieldsize). Not a programmer, did not look at the code yet.

**Describe alternatives you've considered**
I know the size of the field and click that many times, waiting for the cursor to slowly move.

**Additional context**

**Comment by squee72564** [comment]
Hello @andagel, this issue should already be solved with the v1.5 update; I just had my pull request merged with the official flipper zero catalog a few days ago so the most recent updates should be on the [flipper labs site](https://lab.flipper.net/apps/minesweeper_redux).

It should be a setting called "Wrap" in the settings menu. Make sure it is enabled and then the movement should wrap to the other side of the screen. You will see a change in the haptic feedback, sound, and led color displayed when the setting is turned on/off and you try to move across the "edge" of the board.

Would you mind either building from this repo or re-installing from flipper labs to ensure that it is properly updated on your device, and then let me know that everything is working properly?

Thanks for playing!

![Screenshot_20240713_073114](https://github.com/user-attachments/assets/0d155116-0aea-40bc-a0bf-b0005816e593)

**Comment by andagel** [comment]
@squee72564 indeed, I just got the most recent update and the feature is working flawlessly. 
Thank you for the great job!

**Comment by squee72564** [comment]
@andagel Glad to hear it, enjoy!
